### ISSUE TITLE
Kein Exception Handling beim Audio

### ISSUE THREAD

**Issue by 9Lukas5** [pigtastic/ForeverAlonePong#1]
Aus irgendwelchen Gründen funktioniert diese Java Sound Geschichte bei mir nicht
-> wirft exception
-> Programm lässt sich nicht ohne ton Spielen
-> ich hab zur Bewertung den Ton auskommentiert, also keine Sorge, ich habs trotzdem bewertet

**Comment by mrvxk** [comment]
Betrifft alle Dateien aus AppData. Hinweis bei falscher Verwendung hinzugefügt.
