### ISSUE TITLE
Kollission wird manchmal nicht erkannt

### ISSUE THREAD

**Issue by 9Lukas5** [pigtastic/ForeverAlonePong#2]
Ich weiß nicht worans liegt, aber es macht den Eindruck, dass es ein sehr flacher Winkel auslöst.
Muss mann aber Geduld haben bis man endlich mal einen entsprechenden Winkel bekommt, dass der Puck das Feld verlässt.

**Comment by mrvxk** [comment]
Durch den Einheitsvektor kommt es nicht mehr zu solch großen "Sprüngen" innerhalb einer Bewegung des Pucks, somit sollte die Kollission wieder zuverlässig erkannt werden. Ich konnte es nun nicht mehr nachstellen.
