### ISSUE TITLE
Ball Geschwindigkeit wird nicht erhöht

### ISSUE THREAD

**Issue by 9Lukas5** [pigtastic/ForeverAlonePong#3]
Der Ball kennt zwar eine Methode:
https://github.com/pigtastic/ForeverAlonePong/blob/b3a10159f184900319acacc05acde2b724976c26/src/de/pictastic/foreverAlonePong/frames/Ball.java#L140-L142

und im Game gibts eine leere Methode, da müsste man den ball.faster() noch einbauen^^
https://github.com/pigtastic/ForeverAlonePong/blob/b3a10159f184900319acacc05acde2b724976c26/src/de/pictastic/foreverAlonePong/frames/Game.java#L294-L296

**Comment by mrvxk** [comment]
Methode aktualisiert!
